motion_planner_server:
  ros__parameters:
    # List of robots to generate motion plans for
    manipulators: ["abb_irb910sc"]
    # The default moveit group for each manipulator
    default_group_name: "manipulator"
    # Seconds to wait to connect to an action or service server
    timeout_duration: 5
    # Configure the planner_server to query motion plans directly from a move_group
    # node that is running by initializing a move_group_interface.
    # When set to false, the planner_server will initialize planning pipelines
    # to directly compute plans but this has not been implemented yet.
    use_move_group_interfaces: true
    # When planning for multiple robots, set this to true.
    use_namespace: false
    # Tolerance for goal position.
    goal_tolerance: 0.05
    # Maximum seconds to generate a plan.
    planning_time: 5.0
    # Maximum number of replanning attempts
    replan_attempts: 10
    # If true, the cartesian interpolator will check for collisions.
    collision_aware_cartesian_path: false
    # Set true if trajectory should be executed after a plan is generated.
    # The execution is a blocking event.
    execute_trajectory: false
    # The seconds within which the current robot state should be valid.
    get_state_wait_seconds: 0.01

    # Namespaced parameters for each robot when use_namespace is true.
    # Is important to ensure move_group, robot_state_publisher and
    # joint_state broadcaster all have the same namespace.
    # Note: If use_namespace is false, pass these parameters directly.
    abb_irb910sc:
      robot_description: ""
      robot_description_semantic: ""
      group_name: "manipulator"
      # Group specific kinematic properties.
      manipulator:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.005
        kinematics_solver_attempts: 3
