controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

robot_controller_server:
  ros__parameters:
    managed_controllers: ["joint_state_broadcaster", "joint_trajectory_controller"]

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
    gains:
      joint_1:
        p: 0.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        normalize_error: false
      joint_2:
        p: 0.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        normalize_error: false
      joint_3:
        p: 0.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        normalize_error: false
      joint_4:
        p: 0.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        normalize_error: false
      joint_5:
        p: 0.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        normalize_error: false
      joint_6:
        p: 0.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 0.0
        normalize_error: false
