name: Build docker images

on:
  workflow_dispatch:
    inputs:
      ros_distribution:
        description: "ROS 2 distribution"
        required: true
        type: string
        default: "jazzy"
      rmf_branch:
        description: "Branch of open-rmf/rmf repository"
        required: true
        type: string
        default: "main"

jobs:
  build-rmf-image:
    name: Push RMF Docker image to GitHub Packages
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push rmf
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |
            ROS_DISTRO=${{ inputs.ros_distribution }}
            RMF_BRANCH=${{ inputs.rmf_branch }}
          tags: ghcr.io/${{ github.repository }}/rmf:${{ inputs.ros_distribution }}-rmf-${{ inputs.rmf_branch }}
          context: .github/rmf
