name: workcell_editor
on:
  pull_request:
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: ['ros:jazzy-ros-base']
    container:
      image: ${{ matrix.docker_image }}
    timeout-minutes: 30
    steps:
    - name: Deps
      run: |
        apt update && apt install -y git curl libclang-dev libasound2-dev libudev-dev libgtk-3-dev python3-pip python3-vcstool
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@1.75
      with:
        components: clippy, rustfmt
    - name: Install colcon cargo
      run: |
        cargo install --debug cargo-ament-build  # --debug is faster to install
        pip install colcon-cargo --break-system-packages
        pip install colcon-ros-cargo --break-system-packages
    - uses: actions/checkout@v2
    - name: vcs
      # TODO(luca) Go back to cloning a tag when a new version is released with jazzy repos file
      run: |
        git clone https://github.com/ros2-rust/ros2_rust.git
        cd ros2_rust
        git checkout f45a66f47dc727e3ccb13037a6c57923af1446c7
        cd ..
        vcs import . < ros2_rust/ros2_rust_jazzy.repos
    - name: rosdep
      run: |
        rosdep update
        rosdep install --from-paths . -yir
    - name: build
      run: /ros_entrypoint.sh colcon build --packages-up-to nexus_workcell_editor
