name: nightly

# on:
#   schedule:
#     # 2am SGT
#     - cron: '0 18 * * *'

on: [push]

jobs:
  build-nexus-base-image:
    name: Push nexus base docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution: [jazzy]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push nexus-base
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |
            ROS_DISTRO=${{ matrix.ros_distribution }}
            NEXUS_BRANCH=base-docker-images
          tags: ghcr.io/${{ github.repository }}/nexus-base:${{ matrix.ros_distribution }}-latest
          context: .github/docker/nexus-base
